package vn.hust.social.backend.entity.enums.notification;

public enum NotificationType {
    LIKE_POST,
    LIKE_COMMENT,
    COMMENT_POST,
    REPLY_COMMENT,
    FRIEND_REQUEST,
    ACCEPT_FRIEND,
    ASSIGN_CLUB_MODERATOR,
    NEW_EVENT,
    EVENT_REGISTRATION_ACCEPTED,
    EVENT_REGISTRATION_REJECTED,
    INVITE_CLUB_FOLLOW,
    INVITE_CLUB_MANAGE,
    APPLY_CLUB_MANAGE,
    APPROVE_CLUB_APPLICATION,
    REJECT_CLUB_APPLICATION
}
